version: '3.3'

services:

  task_webapp:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    container_name: UserManagement
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app
    environment:
      IN_DOCKER: 1
    ports:
      - "8080:8080"
